### ISSUE TITLE
TypeError: process_node() takes from 5 to 6 positional arguments but 7 were given

### ISSUE THREAD

**Issue by may3rd** [Nukleon84/pyflowsheet#3]
I try to run distillation example but got error message.

Traceback (most recent call last):
  File "/Users/maetee/Github/SFILES2/distillation_tower.py", line 62, in <module>
    img = pfd.draw(ctx)
  File "/Users/maetee/miniforge3/envs/sfiles/lib/python3.9/site-packages/pyflowsheet/core/flowsheet.py", line 176, in draw
    s.draw(ctx, grid, minx, miny)
  File "/Users/maetee/miniforge3/envs/sfiles/lib/python3.9/site-packages/pyflowsheet/core/stream.py", line 22, in draw
    points, startAnchor = self._calculateAutoRoute(minx, miny, grid)
  File "/Users/maetee/miniforge3/envs/sfiles/lib/python3.9/site-packages/pyflowsheet/core/stream.py", line 123, in _calculateAutoRoute
    path, _ = finder.find_path(start, end, grid)
  File "/Users/maetee/miniforge3/envs/sfiles/lib/python3.9/site-packages/pathfinding/finder/a_star.py", line 94, in find_path
    return super(AStarFinder, self).find_path(start, end, graph)
  File "/Users/maetee/miniforge3/envs/sfiles/lib/python3.9/site-packages/pathfinding/finder/finder.py", line 158, in find_path
    path = self.check_neighbors(start, end, grid, open_list)
  File "/Users/maetee/miniforge3/envs/sfiles/lib/python3.9/site-packages/pathfinding/finder/a_star.py", line 78, in check_neighbors
    self.process_node(
TypeError: process_node() takes from 5 to 6 positional arguments but 7 were given

**Comment by Ahmedhassan676** [comment]
same here, even the example mentioned on the homepage returns the same error

**Comment by christofi21** [comment]
Downgrade pathfinding:
pip install pathfinding==1.0.1
